language: cpp

compiler: gcc
env: COMPILER=g++-4.9
addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-4.9','valgrind']

install:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git

script:
  - cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER)
  - make
  - ./test/unittest
  - valgrind --error-exitcode=1 --leak-check=full ./test/unittest
  
after_success:
  - coveralls --exclude test/main.cpp --include src/SimpleSock.cpp --gcov-options '\-lp' --gcov 'gcov-4.9'

