branches:
  only:
    - master

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input  
  - cmd: cmake --version
  - cmd: msbuild /version
  
clone_folder: c:\project\simplesock

platform: x86
configuration: Release

before_build:
  - echo Running cmake...
  - cd c:\projects\simplesock
  - cmake -G "Visual Studio 12 2013"
  - dir c:\projects\simplesock

build:
  project: c:\projects\simplesock\SimpleSock.sln

#test_script:
#  - cd c:\build
#  - unittest.exe
