os: Visual Studio 2015

platform:
  - Win32
#  - x64

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  
clone_folder: c:\build

branches:
  only:
    - master

before_build:
  - echo Running cmake...
  - cd c:\projects\simplesock
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 12 2013"
  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 14 2015 Win64"

build:
  project: c:\projects\simplesock\SimpleSock.sln

#test_script:
#  - cd c:\build
#  - unittest.exe
